---
- hosts: all

  pre_tasks:
    - name: PRE TASKS | 1.0 | Load user variables from configuration
      ansible.builtin.include_vars: config.yml
      failed_when: false

  roles:
    - 'systemfiles.ansible-linux-security'