---
- name: Ensure anacrontab, crontab, and cron.* have safe permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 700
  loop:
    - anacrontab
    - crontab
    - cron.hourly
    - cront.daily
    - cron.weekly
    - cron.monthly
    - cron.d

- name: Ensure proper permissions are set for passwd file
  ansible.builtin.file:
    path: /etc/passwd
    owner: root
    group: root
    mode: 644

- name: Ensure proper permissions are set for the shadow file
  ansible.builtin.file:
    path: /etc/shadow
    owner: root
    group: root
    mode: 600

- name: Ensure proper permissions are set for the gshadow file
  ansible.builtin.file:
    path: /etc/gshadow
    owner: root
    group: root
    mode: 600

