---
- name: Ensure UFW firewall rule manager is installed
  ansible.builtin.apt:
    name: ufw
    state: latest

- name: Ensure UFW is disabled (so we don't get locked out)
  community.general.ufw:
    state: disabled

- name: Set logging to '{{ firewall_logging_mode }}'
  community.general.ufw:
    logging: '{{ firewall_logging_mode }}'

- name: Set default policy to implicit deny
  community.general.ufw:
    default: deny

- name: Allow SSH access only from select subnets
  community.general.ufw:
    rule: allow
    comment: "OpenSSH Access from {{ item }}"
    to_port: "{{ ssh_port }}"
    from_ip: "{{ item }}"
  loop: "{{ firewall_ssh_ip_subnets |list }}"
  when: firewall_ssh_ip_restricted


