---
- name: UFW | 1.0 | Ensure UFW firewall rule manager is installed
  ansible.builtin.apt:
    name: ufw
    state: latest

- name: UFW | 2.0 | Ensure UFW is disabled (so we don't get locked out)
  community.general.ufw:
    state: disabled

- name: UFW | 3.0 | Set logging to '{{ firewall_logging_mode }}'
  community.general.ufw:
    logging: '{{ firewall_logging_mode }}'

- name: UFW | 4.0 | Set default policy to implicit deny
  community.general.ufw:
    default: deny

- name: UFW | 5.0 | Allow all SSH connectivity to target
  community.general.ufw:
    rule: allow
    comment: "OpenSSH Access from ALL"
    to_port: "{{ ssh_port }}"
  when: not firewall_ssh_ip_restricted

- name: UFW | 5.1 | Allow SSH access only from select subnets
  community.general.ufw:
    rule: allow
    comment: "OpenSSH Access from {{ item }}"
    to_port: "{{ ssh_port }}"
    from_ip: "{{ item }}"
  loop: "{{ firewall_ssh_ip_subnets |list }}"
  when: firewall_ssh_ip_restricted


