---
- name: Install UFW firewall rule manager
  ansible.builtin.apt:
    name: ufw
    state: latest

- name: Ensure UFW is disabled (so we don't get locked out)
  community.general.ufw:
    state: disabled

- name: Set logging to 'full'
  community.general.ufw:
    logging: '{{ firewall_logging_mode }}'

- name: Set default policy to implicit deny
  community.general.ufw:
    default: deny

- name: Allow SSH access only from select subnets
  community.general.ufw:
    rule: allow
    comment: "OpenSSH Access from {{ item }}"
    to_port: "{{ firewall_ssh_port }}"
    from_ip: "{{ item }}"
  loop: "{{ firewall_ssh_ip_subnets }}"
  when: firewall_ssh_ip_restricted

- name: Start and enable UFW service
  community.general.ufw:
    state: enabled

- name: Reload UFW to ensure rules are set
  community.general.ufw:
    state: reloaded


