---
- name: Restart UFW
  community.general.ufw:
    state: enabled
  become: true
- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true
- name: Reload Sysctl
  ansible.builtin.command: sysctl --system
  changed_when: no
  become: true
  when: ansible_facts.os_family == "Debian"