---
- name: Ensure {{ boot_mountpoint }} exists and is mounted
  ansible.posix.mount:
    path: "{{ boot_mountpoint }}"
    state: present

- name: Get source block device for {{ boot_mountpoint }}
  ansible.builtin.command: df -T {{ boot_mountpoint }} | tail -1 | cut -d' ' -f1
  changed_when: false
  register: boot_mountsrc

- name: Get UUID of {{ boot_mountpoint }}
  ansible.builtin.command: "lsblk -no UUID {{ boot_mountsrc }}"
  changed_when: false
  register: boot_uuid

- name: Get filesystem of {{ boot_mountpoint }}
  ansible.builtin.command: "lsblk -no FSTYPE {{ boot_mountsrc }}"
  changed_when: false
  register: boot_fstype

- name: Ensure {{ boot_mountpoint }} is locked (ro)
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^UUID={{ boot_uuid.stdout }} {{ boot_mountpoint }} {{ boot_fstype.stdout }} defaults,ro 1 2'
    line: "UUID={{ boot_uuid.stdout }} {{ boot_mountpoint }} {{ boot_fstype.stdout }} defaults,ro 1 2"
