
- name: "(ansible-linux-security) Load OS Specific Variables From File"
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  tags:
  - always

- ansible.builtin.include_tasks:
    file: "Centos.yml"
    apply:
      become: true
      tags:
      - ansible-linux-security-centos
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  tags:
  - ansible-linux-security-centos
  - ansible-linux-security-centos-tasks

- ansible.builtin.include_tasks:
    file: "Ubuntu.yml"
    apply:
      become: true
      tags:
      - ansible-linux-security-ubuntu
  when: ansible_distribution == 'Ubuntu' and ansible_os_family == 'Debian'
  tags:
  - ansible-linux-security-ubuntu
  - ansible-linux-security-ubuntu-tasks