
- name: SYSTEM UPDATE | 1.0 | Update all package sources to latest stable versions
  ansible.builtin.package:
    name: '*'
    state: latest

- name: SYSTEM UPDATE | 2.0 | Install required packages for role
  ansible.builtin.package:
    name: "{{ install_packages }}"
